import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  addImageButton: {
    alignSelf: 'flex-end',
    alignItems: "center", 
    justifyContent: "center", 
    paddingVertical: 8, 
    paddingHorizontal: 8, 
    borderRadius: 8, 
    backgroundColor: "aliceblue", 
    position: "absolute",
    right: 20, 
    top: 50, 
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,

    elevation: 3,
  },
  startButton: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 4,
    backgroundColor: "black",
    position: "absolute",
    bottom: 30,
  },
  cancelRoadtripButton: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 4,
    backgroundColor: "red",
    position: "absolute",
    bottom: 80,
  },
  createButton: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    marginHorizontal: 5,
    borderRadius: 4,
    borderColor: "black",
    borderWidth: 1,
    backgroundColor: "black",
    width: 100,
  },
  cancelButton: {
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 5,
    paddingVertical: 12,
    borderRadius: 4,
    borderColor: "black",
    borderWidth: 1,
    elevation: 3,
    backgroundColor: "white",
    width: 100,
  },
  formButtonContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 20,
  },
  text: {
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "bold",
    letterSpacing: 0.25,
    color: "white",
  },
  modalText: {
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "bold",
    letterSpacing: 0.25,
    position: "centered",
    color: "black",
  },
  centeredView: {
    flex: 1,
    marginTop: 22,
  },
  modalView: {
    margin: 20,
    backgroundColor: "white",
    borderRadius: 20,
    padding: 75,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  whiteBoldTextStyle: {
    color: "white",
    fontWeight: "bold",
    textAlign: "center",
  },
  blackBoldTextStyle: {
    color: "black",
    fontWeight: "bold",
    textAlign: "center",
  },
  modalText: {
    marginBottom: 15,
    textAlign: "center",
  },
  modalTextInput: {
    height: 40,
    width: 200,
    margin: 12,
    borderWidth: 1,
    padding: 10,
  },
});

export default styles;
